# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PB484O7dOqpGP_3t1IoozZN_oHnx2Eqh
"""

!pip install streamlit -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import random
# 
# st.set_page_config(page_title="Ateşli Çift Oyunu 🔥", layout="wide", initial_sidebar_state="expanded")
# 
# st.title("🔥 Nur & Can Ateşli Oyunu 🔥")
# st.markdown("*Seviyeler giderek zorlaşıyor:* 1 = Hafif dokunuş → 4 = Zirve/Extreme 😈")
# 
# # Sidebar
# with st.sidebar:
#     st.header("Durum")
#     if 'skor_kiz' not in st.session_state:
#         st.session_state.skor_kiz = st.session_state.skor_erkek = 0
#         st.session_state.kiyafet_kiz = st.session_state.kiyafet_erkek = 5
# 
#     st.write(f"*Skor* → Nur: {st.session_state.skor_kiz} | Can: {st.session_state.skor_erkek}")
#     st.write(f"*Kıyafet* → Nur: {st.session_state.kiyafet_kiz} | Can: {st.session_state.kiyafet_erkek}")
# 
# # Ana Menü
# st.markdown("### Bölüm Seç")
# col1, col2, col3, col4 = st.columns(4)
# 
# with col1:
#     if st.button("1. Zar Oyunu", use_container_width=True):
#         st.session_state.secim = 1
# 
# with col2:
#     if st.button("3. Seviyeli Tahrik", use_container_width=True):
#         st.session_state.secim = 3
# 
# with col3:
#     if st.button("4. DARE + Soyunma", use_container_width=True):
#         st.session_state.secim = 4
# 
# with col4:
#     if st.button("5. Final Ödül", use_container_width=True):
#         st.session_state.secim = 5
# 
# # Seçilen bölüm
# if 'secim' in st.session_state:
#     sec = st.session_state.secim
#     st.divider()
#     st.subheader(f"Bölüm {sec}")
# 
#     if sec == 1:
#         st.write("Zar at ve pozisyon + yer belirle")
#         if st.button("Zar At 🎲"):
#             pozisyonlar = [
#                 "Missionary – Göz teması kurarak yavaşça",
#                 "Doggy Style – Arkadan kalçaları sık",
#                 "Cowgirl – Üstte oturarak göğüsleri tut",
#                 "Reverse Cowgirl – Sırtı dönük",
#                 "Spooning – Yan yana sarılıp boynu öp",
#                 "69 – Karşılıklı oral",
#                 "Lotus – Oturarak tüm vücut temas",
#                 "Facesitting – Yüzüne otur",
#                 "Standing Doggy – Ayakta arkadan",
#                 "Table – Masa üstünde"
#             ]
#             yerler = [
#                 "Yatak odası", "Mutfak tezgahı", "Banyo/duş", "Salon koltuğu",
#                 "Balkon (gece)", "Araba koltuğu", "Duvar kenarı", "Küvet içinde",
#                 "Masa üstü", "Halı üstü"
#             ]
#             st.success(f"*Pozisyon:* {random.choice(pozisyonlar)}")
#             st.info(f"*Yer:* {random.choice(yerler)}")
#             st.balloons()
# 
#     elif sec == 3:
#         st.write("Seviyeli Tahrik – Her seviye daha zor!")
#         seviye = st.slider("Şu anki seviye", 1, 4, 1)
#         zorluk = ["Hafif dokunuş", "Yoğun tahrik", "Çıplak temas", "Zirve/Extreme"][seviye-1]
#         st.caption(f"Seviye {seviye}: {zorluk}")
# 
#         if st.button("Görev Çek"):
#             if seviye == 1:
#                 gorev = random.choice([
#                     "Boynuna hafif öpücük kondur",
#                     "Saçlarını okşa",
#                     "Kulak memesine üfle",
#                     "İç bacağa hafif dokun (kıyafet üstü)"
#                 ])
#             elif seviye == 2:
#                 gorev = random.choice([
#                     "Göğüslerine kıyafet üstünden masaj yap",
#                     "Kalçalarını kendine çek",
#                     "Boynunu em (kıyafet üstü)"
#                 ])
#             elif seviye == 3:
#                 gorev = random.choice([
#                     "İç bacakları çıplak yala (30 sn)",
#                     "Göğüs uçlarını em",
#                     "Kalçaları çıplak öp"
#                 ])
#             else:
#                 gorev = random.choice([
#                     "Tam oral yap (3 dk)",
#                     "Facesitting + dil kullanımı",
#                     "Doggy + hızlı ritim",
#                     "69 tam oral"
#                 ])
#             st.success(gorev)
#             st.balloons()
# 
#     elif sec == 4:
#         st.write("DARE + Soyunma – Yapmazsan kıyafet çıkar!")
#         oyuncu = random.choice(["Nur", "Can"])
#         dare = random.choice([
#             "30 sn lap dance yap",
#             "En yaramaz fantezini fısılda",
#             "Kıyafet üstünden yavaşça sürtün",
#             "Boynunu 20 sn em",
#             "Göğüslerine masaj yap"
#         ])
#         st.info(f"{oyuncu} için DARE: *{dare}*")
# 
#         col_yes, col_no = st.columns(2)
#         with col_yes:
#             if st.button("Yapıyorum ✅"):
#                 st.success("Harika! Kıyafet çıkmadı 🔥")
#         with col_no:
#             if st.button("Reddediyorum ❌"):
#                 if oyuncu == "Nur":
#                     st.session_state.kiyafet_kiz = max(0, st.session_state.kiyafet_kiz - 1)
#                 else:
#                     st.session_state.kiyafet_erkek = max(0, st.session_state.kiyafet_erkek - 1)
#                 st.error(f"{oyuncu} reddetti! Karşı taraf diyor: 'Tişörtünü / Sütyenini / Pantolonunu çıkar!'")
#                 st.rerun()
# 
#     elif sec == 5:
#         st.write("*Final Skor & Ağır Ödül*")
#         if st.session_state.skor_kiz > st.session_state.skor_erkek:
#             kazanan = "Nur"
#             kaybeden = "Can"
#         elif st.session_state.skor_erkek > st.session_state.skor_kiz:
#             kazanan = "Can"
#             kaybeden = "Nur"
#         else:
#             kazanan = None
# 
#         if kazanan:
#             oduller = [
#                 "3 dakika tam oral (sakso/cunnilingus)",
#                 "Facesitting + dil",
#                 "Doggy + kalça tokatı",
#                 "69 tam oral",
#                 "Rimming + parmak kombin",
#                 "Duvara yasla + ayakta giriş"
#             ]
#             st.success(f"*Kazanan: {kazanan}!*")
#             st.error(f"{kaybeden}'e ödül: {random.choice(oduller)} 😈")
#         else:
#             st.info("Berabere! İkiniz de 1 ağır istek yapın 🔥")
# 
#     if st.button("← Ana Menüye Dön"):
#         del st.session_state.secim
#         st.rerun()
# 
# st.caption("Nur & Can için özel olarak hazırlandı 💕 | Daha fazla madde istersen söyle!")

!streamlit run app.py & npx localtunnel --port 8501